# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Obogdan\OAuthUserBundle\Entity\User:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

    role_hierarchy:
        ROLE_MANAGER: ROLE_WORKER
        ROLE_ADMIN: ROLE_MANAGER

    providers:
        obogdan_hwi_provider:
            id: obogdan.oauth_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    auth0: "/auth0/callback"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: obogdan.oauth_user_provider
            logout:
                path:   /auth0/logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
